import Head from "next/head";
import styles from "./index.module.css";
import Link from "next/link";
import Button from "../../components/Button/Button";
import Twitter from "../../components/icons/Twitter";
import Apple from "../../components/icons/Apple";
import Google from "../../components/icons/Google";
import ButtonClose from "../../components/ButtonClose/ButtonClose";

// PÁGINA DEL REGISTER
const Login = () => {
  return (
    <div className="background">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* CONTENEDOR DE TODO */}
      <div className="container">
        {/* HEADER */}
        <header>
          <Link className="btn-cerrar" href="/">
            <a className="btn-cerrar1">
              <ButtonClose fill={colors.white} />
            </a>
          </Link>
          <Twitter fill="#fff" width={40} />
        </header>
        <main>
          <section>
            {/* TITULO */}
            <h1 className="title">Inicia sesión en Twitter</h1>
            {/* BOTONES DE LOGUEARSE CON GOOGLE O APPLE */}
            <Button type="submit">
              <Google fill="#000" width={24} />
              <span>Iniciar sesión con Google</span>
            </Button>
            <Button type="submit">
              <Apple fill="#000" width={24} />
              <span>Iniciar sesión con Apple</span>
            </Button>
            {/* FORMULARIO PARA LOGUEARSE */}
            <form>
              <input placeholder="Correo electronico" type="text" />
              <input placeholder="Contraseña" type="password" />
              <Button type="submit">
                <span>Iniciar sesión</span>
              </Button>
            </form>
            <p className={styles.text}>
              ¿No tienes una cuenta?{" "}
              <Link href="/registrarse">
                <a>Regístrate</a>
              </Link>
            </p>
          </section>
        </main>
      </div>

      <style jsx>{`
        .background {
          background-color: #273746;
          height: 100vh;
          display: flex;
          justify-content: center;
          align-items: center;
        }
        .container {
          background-color: black;
          min-width: 600px;
          min-height: 600px;
          border-radius: 15px;
          padding: 0.5rem;
          display: flex;
          flex-direction: column;
        }

        header {
          display: flex;
          justify-content: center;
        }

        main {
          padding: 0 5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        section {
          padding: 1rem 4rem;
        }

        .title {
          color: white;
        }

        form {
          width: 100%;
          display: flex;
          flex-direction: column;
          margin-bottom: 2rem;
          margin-top: 1rem;
        }

        input {
          flex: 1;
          width: 100%;
          background-color: black;
          outline: none !important;
          border: 1px solid dimgray;
          padding: 1rem 0.3rem;
          margin-bottom: 1rem;
          transition: 0.1s all ease;
          position: relative;
          color: #fff;
        }

        input:focus {
          border: 1px solid dodgerblue;
        }
        input:focus::placeholder {
          color: dodgerblue;
        }
      `}</style>
    </div>
  );
};

export default Login;
