import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { BiX } from "react-icons/bi";
import Button from "../../components/Button";

// PÁGINA PARA CREAR CUENTA
const CreateAccount = (second) => {
  return (
    <div>
      <Head>
        <title>Regístrate en Twitter / Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* CONTENEDOR DE TODO */}
      <div>
        {/* HEADER */}
        <header>
          <Link href="/">
            <BiX />
          </Link>
          <Image src={Icono} alt="Icono Twitter" />
        </header>
        {/* TITULO */}
        <title>Crea tu cuenta</title>
        {/* FORMULARIO PARA CREAR CUENTA */}
        <form>
          <input placeholder="Correo electrónico" type="email" />
          <input placeholder="Contraseña" type="password" />
          <input placeholder="Repetir contraseña" type="password" />
          {/* BOTON PARA LOGUEARSE */}
          <Button
            text="Crear"
            colorText="black"
            colorBg="white"
            type="submit"
          />
        </form>
      </div>
    </div>
  );
};

export default CreateAccount;
