import Head from "next/head";
import Button from "../components/Button/Button";
import Google from "../components/icons/Google";
import Twitter from "../components/icons/Twitter";
import { useContext, useEffect, useState } from "react";
import { UserContext, USER_STATES } from "../context/UserProvider";
import { useRouter } from "next/router";
import { colors } from "../styles/theme";

// PÁGINA DEL HOME
export default function Home() {
  const [loading, setLoading] = useState(false);
  const { loginGoogle, user } = useContext(UserContext);
  const router = useRouter();

  // Funcion para loguearse con Google
  const onSubmit = async () => {
    try {
      setLoading(true);
      await loginGoogle();
      router.replace("/home");
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  // Efecto para cuando tengamos user ya nos redirecte a home
  useEffect(() => {
    // Si tenemos un uruario nos redirigimos a home
    user && router.replace("/home");
  }, [user]);

  return (
    <>
      <Head>
        <title>Twitter. Es lo que esta pasando ahora.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="background">
        {loading && <p>Loading....</p>}
        <main className="container">
          <div className="icono_twitter">
            <Twitter fill="#fff" width={44} />
          </div>
          <h1>Lo que está pasando ahora</h1>
          <div className="button">
            {user === USER_STATES.NOT_LOGGED && (
              <Button
                onClick={onSubmit}
                type="submit"
                text="Ingresar con Google"
              >
                <Google fill="#000" width={24} />
              </Button>
            )}
            {user === USER_STATES.NOT_KNOWN && <span>Loading...</span>}
          </div>
        </main>
      </div>

      <style jsx>{`
        .background {
          height: 100vh;
          width: 100%;
          background: ${colors.black};
          display: flex;
          justify-content: center;
          padding: 5rem;
        }

        .container {
          display: flex;
          flex-direction: column;
          justify-items: center;
          text-align: center;
          border-radius: 20px;
          background: ${colors.gray2};
          padding: 6rem 2rem 3rem 2rem;
        }

        .button {
          margin-left: 3.3rem;
        }

        @media screen and (max-width: 640px) {
          .container {
            background: ${colors.black};
          }

          .button {
            margin-left: 3rem;
          }
        }

        @media screen and (max-width: 500px) {
          .container {
            background: ${colors.black};
          }

          .button {
            margin-left: 0.4rem;
          }
        }
      `}</style>
    </>
  );
}
