import { BiCog, BiPowerOff } from "react-icons/bi";
import Link from "next/link";
import Head from "next/head";
import Twitter from "../../components/icons/Twitter";
import { colors } from "../../styles/theme";
import ComposeTweet from "../../components/icons/ComposeTweet";
import Search from "../../components/icons/Search";
import { useContext, useEffect, useState } from "react";
import { UserContext } from "../../context/UserProvider";
import { useFirestore } from "../../hooks/useFirestore";
import Tweet from "../../components/Tweet";
import Avatar from "../../components/Avatar";
import ButtonSkyBlue from "../../components/ButtonSkyBlue";
import { useRouter } from "next/router";

const HomePage = () => {
  const { signOutUser } = useContext(UserContext);

  // Sacamos la data, error y loading de useFirestore
  const { data, error, loading, getData, addData, deleteData } = useFirestore();

  // Efecto para cuando carguemos el home, nos traiga la data
  useEffect(() => {
    console.log("getData");
    getData();
  }, []);

  return (
    <div className="background">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* ASIDE IZQUIERDO */}
        <aside className="aside_left">
          <div className="icono_twitter">
            <Link href="/" className="icono_twitter2">
              <a className="icono_twitter1">
                <Twitter width={240} fill={"#fff"} />
              </a>
            </Link>
          </div>
          <Link href="/">
            <a className="enlace">
              <span>#</span>
              <h2>Explorar</h2>
            </a>
          </Link>
          <Link onClick={signOutUser()} href="/">
            <a className="enlace">
              <BiCog />
              <h2>Configuración</h2>
            </a>
          </Link>
          <Link href="/">
            <a className="enlace">
              <BiPowerOff />
              <h2>Cerrar sesión</h2>
            </a>
          </Link>
        </aside>
        {/* TIMELINES DE TWEETS */}
        <section className="timeline">
          {/* EN VEZ DE PASARLE EL TWEET, LE PASAMOS UN OBJETO CON TODAS LAS PROPS DEL TWEET */}
          <div className="button_skyblue">
            <Link href="/compose">
              <a>
                <ButtonSkyBlue text="Twittear" type="button" />
              </a>
            </Link>
          </div>
          <div>
            {data.map(
              ({ id, userName, avatar, content, userId, createdAt, img }) => {
                return (
                  // El tweet va a contener todas estas props
                  <Tweet
                    key={id}
                    userName={userName}
                    avatar={avatar}
                    content={content}
                    id={id}
                    img={img}
                    userId={userId}
                    createdAt={createdAt}
                  />
                );
              }
            )}
          </div>
        </section>
        {/* ASIDE DERECHO */}
        <aside className="aside_right">
          {/* CONTENEDOR DE TENDENCIAS */}
          <div className="search">
            <div className="icon_search">
              <Search fill="#525252" />
            </div>
            <input
              type="text"
              placeholder="Buscar en Twitter"
              className="input"
            />
          </div>
          <div className="contenedor_tendencias">
            <h2 className="titulo_tendencias">Qué está pasando</h2>
            {/* TENDENCIA 1 */}
            <Link href="/">
              <div className="contenedor_tendencia">
                <div className="izq_tendencia">
                  <div className="tag_tendencia">
                    <p className="parrafo_tendencia">Esports * EN DIRECTO</p>
                    <span className="titulo_tendencia">PGL Major Amberes</span>
                    <p>
                      Tendencias sobre{" "}
                      <Link href="/">
                        <a className="enlace_tendencia">Fallen</a>
                      </Link>
                    </p>
                  </div>
                </div>
                <div className="dere-tendencia"></div>
              </div>
            </Link>
            {/* TENDENCIA 2 */}
            <Link href="/">
              <div className="contenedor_tendencia">
                <div className="izq_tendencia">
                  <div className="tag_tendencia">
                    <p className="parrafo_tendencia">Esports * EN DIRECTO</p>
                    <span className="titulo_tendencia">PGL Major Amberes</span>
                    <p className="parrafo2_tendencia">
                      Tendencias sobre{" "}
                      <Link href="/">
                        <a className="enlace_tendencia">Fallen</a>
                      </Link>
                    </p>
                  </div>
                </div>
                <div className="dere-tendencia"></div>
              </div>
            </Link>
            <Link href="/">
              <a className="enlace_mostrar">Mostras más</a>
            </Link>
          </div>
          <p>
            <Link href="/">
              <a className="parrafo_footer">Condiciones de Servicio</a>
            </Link>{" "}
            <Link href="/">
              <a className="parrafo_footer">Política de Privacidad</a>
            </Link>{" "}
            <Link href="/">
              <a className="parrafo_footer">Política de cookies</a>
            </Link>{" "}
            <Link href="/">
              <a className="parrafo_footer">Accesibilidad</a>
            </Link>{" "}
            <Link href="/">
              <a className="parrafo_footer">Información de anuncios</a>
            </Link>{" "}
            <Link href="/">
              <a className="parrafo_footer">Más opciones</a>
            </Link>
          </p>
          <p className="parrafo2_footer">&#169; 2022 Twitter, Inc.</p>
        </aside>
        <button className="btn_tweet">
          <Link href="/compose">
            <a>
              <ComposeTweet fill="#fff" />
            </a>
          </Link>
        </button>
      </div>

      <style jsx>{`
        .background {
          background-color: ${colors.black};
          width: 100%;
          height: 100vh;
        }

        .container {
          display: flex;
          padding: 0 18rem;
          width: 100%;
        }

        /*======================== PARTE IZQUIERDA =====================*/
        .aside_left {
          width: 25%;
          padding: 0.5rem 1.5rem;
          display: flex;
          flex-direction: column;
        }

        .icono_twitter {
          display: flex;
          align-items: center;
          justify-center: flex-start;
          text-align: left;
        }

        .enlace {
          display: flex;
          justify-content: flex-start;
          text-align: left;
          align-items: center;
          text-decoration: none;
          color: ${colors.white};
          border-radius: 30px;
          padding: 0rem;
          margin-botton: 3rem;
        }

        .enlace h2 {
          margin-left: 1rem;
        }

        /*======================== PARTE CENTRAL =====================*/

        .button_skyblue {
          margin-top: 1rem;
          display: flex;
          justify-content: center;
        }

        .timeline {
          width: 45%;
          border-left: 1px solid ${colors.gray2};
          border-right: 1px solid ${colors.gray2};
          height: 100vh;
          display: flex;
          flex-direction: column;
        }

        /*======================= PARTE DERECHA ======================*/
        .aside_right {
          width: 30%;
          padding: 0.5rem 1.5rem;
          display: flex;
          flex-direction: column;
        }

        /* INPUT SEARCH */
        .search {
          width: 100%;
          margin-bottom: 1rem;
          position: relative;
        }

        .icon_search {
          position: absolute;
          top: 0.8rem;
          right: 16.3rem;
        }

        .input {
          width: 100%;
          border: none;
          border-radius: 30px;
          padding: 0.8rem 0 0.8rem 4rem;
          font-size: 14px;
          background-color: ${colors.gray2};
          color: ${colors.white};
        }

        .input:focus {
          outline: none;
          border: 1.5px solid ${colors.skyblue};
        }

        /* TENDENCIA CONTENEDOR */
        .contenedor_tendencias {
          display: flex;
          flex-direction: column;
          background-color: ${colors.gray2};
          border-radius: 18px;
          padding: 0.9rem 0.8rem;
        }

        .titulo_tendencias {
          font-size: 21px;
        }

        /* CONTENEDOR DE CADA TENDENCIA */
        .contenedor_tendencia {
          display: flex;
          width: 100%;
        }

        .izq_tendencia {
          width: 70%;
        }

        .tag_tendecia {
          display: flex;
          flex-direction: column;
        }

        .parrafo_tendencia {
          font-size: 14px;
          color: ${colors.gray};
        }

        .parrafo2_tendencia {
          font-size: 15px;
          color: ${colors.gray};
        }

        .titulo_tendencia {
          font-weight: 700;
        }

        .enlace_tendencia {
          text-decoration: none;
          color: ${colors.skyblue};
        }

        .enlace_mostrar {
          text-decoration: none;
          font-weight: 400;
          color: ${colors.skyblue};
        }

        .parrafo_footer {
          text-decoration: none;
          font-size: 14px;
          color: ${colors.gray};
        }

        .parrafo2_footer {
          font-size: 14px;
          color: ${colors.gray};
        }

        /* BOTON PARA HACER TWEETS */
        .btn_tweet {
          background-color: ${colors.skyblue};
          border: none;
          border-radius: 9999px;
          height: 60px;
          width: 60px;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          position: fixed;
          right: 19rem;
          bottom: 2rem;
          visibility: hidden;
        }

        /* MEDIA QUERIES */

        @media screen and (max-width: 650px) {
          .container {
            padding: 0rem;
          }

          .aside_left {
            display: none;
          }

          .button_skyblue {
            display: none;
          }

          .timeline {
            width: 100%;
          }

          .aside_right {
            display: none;
          }

          .btn_tweet {
            right: 4rem;
            visibility: visible;
          }
        }

        @media screen and (max-width: 500px) {
          .container {
            padding: 0rem;
          }

          .aside_left {
            display: none;
          }

          .timeline {
            width: 100%;
          }

          .aside_right {
            display: none;
          }
        }
      `}</style>
    </div>
  );
};

export default HomePage;
