import IconoTwitter from "../../public/logotwitter.png";
import { BiCog, BiPowerOff } from "react-icons/bi";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const HomePage = (second) => {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ASIDE IZQUIERDO */}
      <aside>
        <Link href="#">
          <Image src={IconoTwitter} alt="Logo de Twitter" />
        </Link>
        <Link href="#">
          <button>
            <h2>#</h2>
            <h2>Explorar</h2>
          </button>
        </Link>
        <Link href="#">
          <button>
            <BiCog />
            <h2>Configuración</h2>
          </button>
        </Link>
        <Link>
          <button>
            <BiPowerOff />
            <h2>Cerrar sesión</h2>
          </button>
        </Link>
      </aside>
      {/* TIMELINES DE TWEETS */}
      <div></div>
      {/* ASIDE DERECHO */}
      <aside>
        {/* CONTENEDOR DE TENDENCIAS */}
        <div>
          <header>Qué está pasando</header>
          {/* TENDENCIA 1 */}
          <Link href="#">
            <div className="contenedor-tendencia">
              <div className="izq-tendencia">
                <div className="tag-tendencia">
                  <p>Esports * EN DIRECTO</p>
                  <span>PGL Major Amberes</span>
                  <p>
                    Tendencias sobre{" "}
                    <Link>
                      <a>Fallen</a>
                    </Link>
                  </p>
                </div>
              </div>
              <div className="dere-tendencia"></div>
            </div>
          </Link>
          {/* TENDENCIA 2 */}
          <Link href="#">
            <div className="contenedor-tendencia">
              <div className="izq-tendencia">
                <div className="tag-tendencia">
                  <p>Esports * EN DIRECTO</p>
                  <span>PGL Major Amberes</span>
                  <p>
                    Tendencias sobre{" "}
                    <Link>
                      <a>Fallen</a>
                    </Link>
                  </p>
                </div>
              </div>
              <div className="dere-tendencia"></div>
            </div>
          </Link>
          <Link>
            <a>Mostras más</a>
          </Link>
        </div>
        <p>
          <Link href="#">
            <a>Condiciones de Servicio</a>
          </Link>{" "}
          <Link href="#">
            <a>Política de Privacidad</a>
          </Link>{" "}
          <Link href="#">
            <a>Política de cookies</a>
          </Link>{" "}
          <Link href="#">
            <a>Accesibilidad</a>
          </Link>{" "}
          <Link href="#">
            <a>Información de anuncios</a>
          </Link>{" "}
          <Link href="#">
            <a>Más opciones</a>
          </Link>
        </p>
        <p>&#169; 2022 Twitter, Inc.</p>
      </aside>
    </div>
  );
};

export default HomePage;
