import Head from "next/head";

// PÁGINA PARA TWEETEAR
const ComposeTweet = (second) => {
  return (
    <div>
      <Head>
        <title>Crear un tweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* FORMULARIO PARA TWITTEAR */}
      <section>
        <form>
          <textarea></textarea>
          <section></section>
          <div></div>
        </form>
      </section>
    </div>
  );
};

export default ComposeTweet;
